# Generated by Django 5.2.6 on 2025-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('pain', 'Pain Relief'), ('cold', 'Cold & Flu'), ('vitamins', 'Vitamins & Supplements'), ('diabetes', 'Diabetes'), ('cardio', 'Cardiology'), ('skin', 'Skin Care'), ('antibiotics', 'Antibiotics')], max_length=20)),
                ('description', models.TextField()),
                ('components', models.TextField()),
                ('side_effects', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='medicines/')),
            ],
        ),
    ]
